//
// This source file is part of the Pylon open source project.
//
// Copyright (c) 2026 Jaldis B.V.
//
// Licensed under the MIT OR Apache-2.0 license (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://opensource.org/licenses/MIT
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

import type {LRParser} from "@lezer/lr";
import {LRLanguage, LanguageSupport} from "@codemirror/language";
import {styleTags, tags as t} from "@lezer/highlight";

// @ts-ignore — generated by `npm run generate:pyql-lang`, no type declarations
import {parser as _parser} from "./lang";

const parser = _parser as LRParser;

// This grammar is mostly syntax-generic — identifiers, strings, casts,
// $params, module::name — with PyQL-specific keywords isolated in meta.js.
// Keywords can be trimmed or extended as real PyQL syntax differences are
// discovered.
export const pyqlLanguage = LRLanguage.define({
  parser: parser.configure({
    props: [
      styleTags({
        BuiltinName: t.standard(t.name),
        Bool: t.bool,
        Comment: t.comment,
        Name: t.name,
        ModuleName: t.special(t.name),
        Keyword: t.keyword,
        Operator: t.operator,
        "RawStringPrefix ByteStringPrefix": t.special(t.string),
        "String ByteString": t.string,
        "StringEscape ByteEscape": t.escape,
        Number: t.number,
        BigNumberPostfix: t.special(t.number),
        Punctuation: t.punctuation,
        QueryParameterName: t.variableName,
        "( )": t.paren,
        "{ }": t.brace,
        "[ ]": t.squareBracket,
      }),
    ],
  }),
  languageData: {
    closeBrackets: {brackets: ["[", "{", "(", '"', "'"]},
    indentOnInput: /^\s*[\}]$/,
    commentTokens: {line: "#"},
  },
});

export const pyql = () => new LanguageSupport(pyqlLanguage);
